"""login fields

Revision ID: 2b6ef29be75c
Revises: 4f6691851c71
Create Date: 2021-04-22 11:48:10.838347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6ef29be75c'
down_revision = '4f6691851c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_doctor_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_doctor_name'), ['name'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=25), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_patient_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_patient_email'), type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_doctor_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_doctor_email'), type_='unique')

    # ### end Alembic commands ###
